/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz.gui;

import java.awt.Font;
import quiz.pojo.UserLogin;

/**
 *
 * @author yasi
 */
public class AdminScreenFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentScreen
     */
    public AdminScreenFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblHi.setText(lblHi.getText()+" "+UserLogin.getUserName()+"!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jrbSetpaper = new javax.swing.JRadioButton();
        jrbEditpaper = new javax.swing.JRadioButton();
        jrbRegister = new javax.swing.JRadioButton();
        jrbViewscore = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();
        lblHi = new javax.swing.JLabel();
        lblLog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Online Quiz Administration Panel");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Make a choice");

        jrbSetpaper.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbSetpaper);
        jrbSetpaper.setForeground(new java.awt.Color(255, 153, 153));
        jrbSetpaper.setText("Set a paper");
        jrbSetpaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSetpaperActionPerformed(evt);
            }
        });

        jrbEditpaper.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbEditpaper);
        jrbEditpaper.setForeground(new java.awt.Color(255, 153, 153));
        jrbEditpaper.setText("Edit paper");

        jrbRegister.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbRegister);
        jrbRegister.setForeground(new java.awt.Color(255, 153, 153));
        jrbRegister.setText("Register students");

        jrbViewscore.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbViewscore);
        jrbViewscore.setForeground(new java.awt.Color(255, 153, 153));
        jrbViewscore.setText("View score");

        btnDoTask.setBackground(new java.awt.Color(0, 0, 0));
        btnDoTask.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDoTask.setForeground(new java.awt.Color(255, 51, 51));
        btnDoTask.setText("Do task");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });

        lblHi.setBackground(new java.awt.Color(0, 0, 0));
        lblHi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHi.setForeground(new java.awt.Color(51, 153, 255));
        lblHi.setText("Hello");

        lblLog.setBackground(new java.awt.Color(0, 0, 0));
        lblLog.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLog.setForeground(new java.awt.Color(51, 153, 255));
        lblLog.setText("Logout");
        lblLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLog))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(186, 186, 186)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbEditpaper)
                                    .addComponent(jrbSetpaper)
                                    .addComponent(jrbRegister)
                                    .addComponent(jrbViewscore)
                                    .addComponent(btnDoTask)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jLabel2)))
                        .addGap(0, 32, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHi)
                    .addComponent(lblLog))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jrbSetpaper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbEditpaper)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbViewscore)
                .addGap(18, 18, 18)
                .addComponent(btnDoTask)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogMouseClicked
        // TODO add your handling code here:
        this.dispose();
        LoginFrame lf=new LoginFrame();
        lf.setVisible(true);
    }//GEN-LAST:event_lblLogMouseClicked

    private void lblLogMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogMouseEntered
        // TODO add your handling code here:
        Font f=new Font("Tahoma",Font.ITALIC,12);
        lblLog.setFont(f);
    }//GEN-LAST:event_lblLogMouseEntered

    private void lblLogMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblLogMouseExited

    private void jrbSetpaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSetpaperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbSetpaperActionPerformed

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed
        // TODO add your handling code here:
        if(jrbSetpaper.isSelected()){
            SetPaper paper=new SetPaper();
            paper.setVisible(true);
            this.dispose();
            }
         if(jrbEditpaper.isSelected()){
            PaperEditingFrame paperef=new PaperEditingFrame();
            paperef.setVisible(true);
            this.dispose();
            }
         if(jrbRegister.isSelected()){
            StudentRegisFrame regis=new StudentRegisFrame();
            regis.setVisible(true);
            this.dispose();
            }
         if(jrbViewscore.isSelected()){
            ViewScorePanel vsp=new ViewScorePanel();
            vsp.setVisible(true);
            this.dispose();
            }
    }//GEN-LAST:event_btnDoTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminScreenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminScreenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminScreenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminScreenFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminScreenFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoTask;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbEditpaper;
    private javax.swing.JRadioButton jrbRegister;
    private javax.swing.JRadioButton jrbSetpaper;
    private javax.swing.JRadioButton jrbViewscore;
    private javax.swing.JLabel lblHi;
    private javax.swing.JLabel lblLog;
    // End of variables declaration//GEN-END:variables
}
